// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Mock: typeof import('./src/components/Mock.vue')['default']
    Pinia: typeof import('./src/components/Pinia.vue')['default']
  }
}

export { }
